apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: netflix-frontend
  template:
    metadata:
      labels:
        app: netflix-frontend
    spec:
      containers:
      - name: netflix-frontend
        image: shacharavraham/netflix-images-frontend:v1.0.14
        ports:
        - containerPort: 3000
        env:
        - name: MOVIE_CATALOG_SERVICE
          value: "http://netflix-movie-catalog:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-frontend
spec:
  selector:
    app: netflix-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: LoadBalancer
