apiVersion: apps/v1
kind: Deployment
metadata:
  name: netflix-movie-catalog
spec:
  replicas: 2
  selector:
    matchLabels:
      app: netflix-movie-catalog
  template:
    metadata:
      labels:
        app: netflix-movie-catalog
    spec:
      containers:
      - name: netflix-movie-catalog
        image: shacharavraham/netflix-images-api:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: netflix-movie-catalog
spec:
  selector:
    app: netflix-movie-catalog
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP